-- changeset liquibase:11
CREATE TABLE table1 (
    ID1 INTEGER NOT NULL, 
 NAME2 VARCHAR2(50 BYTE) NOT NULL, 
     ACTIVE NUMBER(1, 0) DEFAULT 1, 
        CONSTRAINT PK_DEPARTMENT54 PRIMARY KEY (ID1));

-- changeset liquibase:12
CREATE TABLE table2 (
      ID2 INTEGER NOT NULL, 
 NAME3 VARCHAR2(50 BYTE) NOT NULL, 
     ACTIVE NUMBER(1, 0) DEFAULT 1, 
        CONSTRAINT PK_DEPARTMENT55 PRIMARY KEY (ID2));

-- changeset liquibase:13
CREATE TABLE table3 (
      ID3 INTEGER NOT NULL, 
 NAME4 VARCHAR2(50 BYTE) NOT NULL, 
     ACTIVE NUMBER(1, 0) DEFAULT 1, 
        CONSTRAINT PK_DEPARTMENT54 PRIMARY KEY (ID3));